### ISSUE TITLE
Running main example

### ISSUE THREAD

**Issue by u473t8** [jacamo-lang/camel-cartago#2]
When I run the main example, mas console gives the following output:

```
java.lang.ClassNotFoundException: artifactComponent.ArtifactCamel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:332)
	at jacamo.infra.JaCaMoLauncher.createCustomPlatforms(JaCaMoLauncher.java:222)
	at jacamo.infra.JaCaMoLauncher.create(JaCaMoLauncher.java:265)
	at jacamo.infra.JaCaMoLauncher.main(JaCaMoLauncher.java:62)
CArtAgO Http Server running on http://127.0.1.1:3273
Jason Http Server running on http://127.0.1.1:3272
[alice] -----Agent started
[bob] -----Agent started
[bob] No failure event was generated for +!start[code(focus(dummyArtifact)),code_line(5),code_src("bob.asl"),env_failure_reason(wrong_op_arguments(cobj_2,"focus/1")),error(action_failed),error_msg("Wrong operation arguments: operation focus on artifact workspace (type: cartago.WorkspaceArtifact)
- expected 1 parameter(s) - types: class cartago.ArtifactId
- actual parameter(s): dummyArtifact type: class java.lang.String"),source(self)]
intention 1: 
    +!start[source(self)] <- ... focus(dummyArtifact) / {}

[alice] No failure event was generated for +!start[code(focus(dummyArtifact)),code_line(7),code_src("alice.asl"),env_failure_reason(wrong_op_arguments(cobj_2,"focus/1")),error(action_failed),error_msg("Wrong operation arguments: operation focus on artifact workspace (type: cartago.WorkspaceArtifact)
- expected 1 parameter(s) - types: class cartago.ArtifactId
- actual parameter(s): dummyArtifact type: class java.lang.String"),source(self)]
intention 2: 
    +!start[source(self)] <- ... focus(dummyArtifact); !updateCycle / {}
```
It seems that camel-cartago artifact was not created.

**Comment by Sergio-PB** [comment]
Yes, it seems the component itself was not loaded.
Are you running it with the gradle.build presented in the folder?

**Comment by u473t8** [comment]
I run `gradle.build` located on path `camel-cartago/examples/main_example`. It looks a bit strange that in the dependencies section a camel-jason component is specified, not camel-cartago: 
`compile group: 'org.jacamo-lang',     name: 'camel-jason' ,   version: '1.0'`

**Comment by Sergio-PB** [comment]
Your observation makes sense. There is no dependency for the camel-cartago has not been yet published. You have to run `gradle build` in the root, locate the .jar in build/libs and copy into 
`main_example/lib`. That's why the `build.gradle` contains 
`compile fileTree(dir: 'lib', include: ['*.jar'])`
to compile the .jar .

**Comment by u473t8** [comment]
Thank you, that works. Maybe these instructions worth mentioning in _How To Use_ section of readme.

**Comment by Sergio-PB** [comment]
The component has been now published, and the gradle.build updated.
Thank you for the notice
